language: c

addons:
  apt:
    packages:
      - cmake
      - g++
      - libgmp-dev
      - libopenal-dev
      - libsndfile1-dev
      - libzip-dev
      - pkg-config

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack --version

script:
  - cd src
  - mkdir -p cpp/dist
  - (cd cpp/dist && cmake .. && make)
  - export STACK_YAML=$PWD/stack-libzip-0.10.yaml
  - stack setup --no-terminal
  - stack test --no-terminal

cache:
  directories:
    - $HOME/.stack
